### ISSUE TITLE
RecSys TODO - Medium Term

### ISSUE THREAD

**Issue by suranah** [abhijithch/JuliaRecSys.jl#6]
#### API & Interfaces

- [ ] Read from various file formats
- [ ] Output results to different formats
- [ ] Functions to test and benchmark the quality of recommendation system 
- [ ] Cross-fold datasets and testing

#### New Recommendation Algorithms & Techniques

- [ ] SGD matrix factorization
- [ ] Neighborhood methods
- [ ] Functions for assesing user and item similarity
